Remove production check

diff --git a/.github/workflows/nightly-scan.yml b/.github/workflows/nightly-scan.yml
--- a/.github/workflows/nightly-scan.yml
+++ b/.github/workflows/nightly-scan.yml
@@ -18,6 +18,44 @@ jobs:
           cat ./image-matrix.json >> $GITHUB_OUTPUT
           echo 'EOF' >> $GITHUB_OUTPUT
 
+  trivy-scan:
+    runs-on: ubuntu-latest
+    needs:  get-matrix-values
+    strategy:
+      matrix:
+        image: ${{fromJSON(needs.get-matrix-values.outputs.image)}}
+    steps:
+      - uses: actions/checkout@v5
+
+      - name: Set job environment variables
+        run:  cat JOB.env >> $GITHUB_ENV
+
+      - name: Run Aqua Trivy scan
+        id: trivy-scan
+        uses: aquasecurity/trivy-action@0.33.1
+        with:
+          image-ref: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-node${{matrix.image.pythonVersion}}
+          format: sarif
+          output: trivy-reports-python-${{ matrix.image.pythonVersion }}
+          exit-code: 1
+          vuln-type: os,library
+          trivyignores: '.trivyignore'
+          severity: CRITICAL,HIGH,MEDIUM
+          limit-severities-for-sarif: true
+        continue-on-error: true
+
+      - name: Upload Trivy SARIF report
+        if: ${{ steps.trivy-scan.outcome == 'failure' }}
+        uses: actions/upload-artifact@v5
+        with:
+          name: trivy-reports-python-${{ matrix.image.pythonVersion }}
+
+      - name: Fail build if scan failed
+        if: ${{ steps.trivy-scan.outcome == 'failure' }}
+        run: |
+          echo "Trivy scan failed. Failing the build."
+          exit 1
+
   anchore-scan:
     runs-on: ubuntu-latest
     needs:  get-matrix-values
@@ -32,27 +70,11 @@ jobs:
       
       - name: Run Anchore Grype scan
         id: grype-scan
-        if: ${{ matrix.target == 'production' }}
         uses: anchore/scan-action@v7.2.0
         with:
           image: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-python${{matrix.image.pythonVersion}}
           fail-build: true
           severity-cutoff: "medium"
-        continue-on-error: true
-
-      - name: Run Aqua Trivy scan
-        id: trivy-scan
-        if: ${{ matrix.target == 'production' }}
-        uses: aquasecurity/trivy-action@0.33.1
-        with:
-          image-ref: defradigital/${{env.IMAGE_NAME}}:${{env.DEFRA_VERSION}}-python${{matrix.image.pythonVersion}}
-          format: sarif
-          output: trivy-reports-python-${{ matrix.image.pythonVersion }}
-          exit-code: 1
-          vuln-type: os,library
-          trivyignores: '.trivyignore'
-          severity: CRITICAL,HIGH,MEDIUM
-          limit-severities-for-sarif: true
         continue-on-error: true
 
       - name: Upload Grype SARIF report
@@ -62,15 +84,8 @@ jobs:
           name: grype-reports-python-${{ matrix.image.pythonVersion }}
           path: ${{ steps.grype-scan.outputs.sarif }}
 
-      - name: Upload Trivy SARIF report
-        if: ${{ steps.trivy-scan.outcome == 'failure' }}
-        uses: actions/upload-artifact@v5
-        with:
-          name: trivy-reports-python-${{ matrix.image.pythonVersion }}
-          path: trivy-reports-python-${{ matrix.image.pythonVersion }}
-
       - name: Fail build if scans failed
-        if: ${{ (steps.grype-scan.outcome == 'failure' || steps.trivy-scan.outcome == 'failure') }}
+        if: ${{ (steps.grype-scan.outcome == 'failure') }}
         run: |
           echo "One or more scans failed. Failing the build."
           exit 1
